services:
  app:
    image: ghcr.io/sachinsharma-lordheydes/vanijay-buyer:latest
    container_name: vanijay-app
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-vanijay}
      - HOSTNAME=0.0.0.0
    env_file: .env
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: vanijay-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: pgvector/pgvector:pg16
    container_name: vanijay-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-vanijay}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"

volumes:
  postgres_data:

networks:
  default:
    name: vanijay-network
